#!/usr/bin/env sh

set -e;

bindir="$(composer config --global data-dir)/$(composer config --global bin-dir)"
export PATH="${bindir}:${PATH}"

# Install hirak/prestissimo when not exists
composer global show -q hirak/prestissimo 2> /dev/null || composer global require hirak/prestissimo --no-interaction --no-scripts

exec /docker-entrypoint.sh "$@"
